package com.inti.model;
// Generated 6 mars 2023, 10:39:09 by Hibernate Tools 5.6.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable {

	private int id;
	private String nom;
	private String adresse;
	private Set clients = new HashSet(0);

	public Restaurant() {
	}

	public Restaurant(int id) {
		this.id = id;
	}

	public Restaurant(int id, String nom, String adresse, Set clients) {
		this.id = id;
		this.nom = nom;
		this.adresse = adresse;
		this.clients = clients;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

}
